### PR TITLE
Fix right byte order in frame length encoding

### PR DESCRIPTION
**Pull request by murillo128**

### CODE REVIEW

**Comment by ranganathanm** [comment]
Vlad, please take a look and comment if this is OK.

**Comment by vladimirralev** [comment]
So am trying this patch against the selftest with large payload and it fails. Something else is probably needed on the client side. I will check it out.

**Comment by vladimirralev** [comment]
I will work on https://github.com/usnistgov/jsip/issues/14 . Multiple extra things need to be done.

**Comment by murillo128** [comment]
FWIW patch has been tested on real server against chrome and works. Unit test would be needed anyway.

**Comment by vladimirralev** [comment]
Perhaps you are testing with smaller frames or varying size frames or just one side. I don't see how the large frames can be decoded properly to begin with:
`				long value = 0;
				for(int q=0;q<8;q++) {
					value &= (0xff&readNextByte())<<(7-q)*8;
				}`
It just ANDs everything with a zero. And then there a buffer limit. I will sort it out.

**Comment by murillo128** [comment]
This patch is only for encoding

**Comment by vladimirralev** [comment]
Right, @ranganathanm you can merge this, I will add my stuff later on top.

**Pull request merged**
